# Site settings
baseURL = "https://patricklduffy.com/"
languageCode = "en-US"
title = "Patrick Duffy"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Patrick Duffy"
  description = "Data Analysis and Visualization. R. Reproducibility. STEM Education."
  shareImage = "images/pld17.jpg"
  twitterHandle = "patrickduffy134"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2017 Patrick Duffy"

  # Section - Content
  [params.content]
    name = "Patrick Duffy"
    tagline = "Data Analysis and Visualization. R. Reproducibility. STEM Education."
    bio = "I started in STEM education and work currently in data analysis and instructional design. I'm an avid and constantly-learning R user, dad, mountain biker, and surely other things."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/pld17.jpg"
      position = "center center"


  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Twitter"
        url = "https://twitter.com/patrickduffy134"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:patricklduffy34@gmail.com"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Professional"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/plduffy"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/patrick-duffy-471a86a8/"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
